name: Build Sniper
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JSON Library
        run: |
          mkdir include
          Invoke-WebRequest -Uri "https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp" -OutFile "include/json.hpp"
          mkdir include/nlohmann
          Copy-Item "include/json.hpp" -Destination "include/nlohmann/json.hpp"

      - name: Build with MSVC
        run: |
          cl.exe /EHsc /I include /O2 main.cpp /link /OUT:sniper.exe user32.lib advapi32.lib

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: RobloxSniper
          path: sniper.exe
